fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: gofmt
        name: go fmt
        description: format golang
        entry: gofmt -l -w
        language: golang
        files: \.go$
        args: [ ]
      - id: govet
        name: go vet
        description: go vet
        entry: bash -c 'go vet ./...'
        language: golang
        files: \.go$
        args: [ ]
      - id: golangci-lint
        name: golangci-lint
        description: Run golangci-lint
        entry: golangci-lint run
        language: system
        files: \.go$
        pass_filenames: false
        always_run: true
      - id: go-test
        name: go test
        description: go test project
        entry: bash -c 'go test -v ./...'
        language: golang
